Task 1

In [3]:
import numpy as np

In [7]:
a = np.ones([5,2], dtype = int)

In [8]:
a

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [16]:
a = np.array([[1, 6], [2, 8], [3, 11],[3, 10], [1, 7]])

In [17]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [32]:
mean_a = np.mean(a, axis = 0)

In [33]:
mean_a

array([2. , 8.4])

Task 2

In [37]:
a_centered = a-mean_a

In [38]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Task 3

In [42]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [43]:
a_centered_sp

8.0

In [46]:
num = a_centered_sp / (a_centered.shape[0] - 1)

In [47]:
num

2.0

Task 4

In [48]:
cov = np.cov(a.T)[0, 1]

In [49]:
cov

2.0